version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - db_data:/var/lib/mysql

  myapp:
    build: .
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      MYSQLDB_HOST: mysqldb
      MYSQLDB_ROOT_PASSWORD: 123456
      MYSQLDB_DOCKER_PORT: 3306
      MYSQLDB_DATABASE: ecommerce
    ports:
      - "3000:3000"

volumes:
  db_data:
